name: Test, build and deploy
on: [push, pull_request]

env:
  DOCKER_IMAGE: pandrei7/proiect-la-idp
  WEBHOOK_URL: https://f584-188-26-173-244.eu.ngrok.io/api/webhooks/672246ae-cbaa-4334-91dc-7d37ee3a9fbb

jobs:
  pipeline:
    name: All actions
    runs-on: ubuntu-latest
    timeout-minutes: 40

    env:
      NODE_VERSION: 16.14.0
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
      NG_CLI_ANALYTICS: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install node.js packages
        run: npm install

      - name: Run backend tests
        run: |
          chmod +x mvnw
          npm run backend:info
          npm run backend:nohttp:test
          npm run backend:unit:test

      - name: Build the image
        if: github.event_name == 'push'
        run: |
          mvn clean install -Dmaven.test.skip=true
          ./mvnw verify -DskipTests -Pprod jib:dockerBuild -Djib.to.image='${{ env.DOCKER_IMAGE }}'

      - name: Publish the image
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push "${{ env.DOCKER_IMAGE }}"

      - name: Notify container about change (deploy)
        if: github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy]')
        run: |
          curl -XPOST "${{ env.WEBHOOK_URL }}"
