version: '3.8'
services:
  proiect-emailSender:
    image: proiect
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
    ports:
      - 8081:8080
