# Sample global config for monitoring applications
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['proiect-prometheus:9090']

  - job_name: 'postgres-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'rabbitmq:15692' ]
